# Generated by Django 5.1.3 on 2024-11-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.program'),
        ),
    ]
